Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 20

Style/AsciiComments:
  Enabled: false
