Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 20

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

StringLiterals:
  EnforcedStyle: single_quotes
